import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/components/layout/NavBar";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/lib/context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Online Diary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-col gap-5 bg-dark-background p-20 text-gray-200 max-sm:p-10 max-xs:p-5`}
      >
        <AuthContextProvider>
          <NavBar />
          <div className="m-auto w-9/12 flex-1 px-3 max-mdl:w-full">
            {children}
          </div>
        </AuthContextProvider>
        <footer className="mt-40 shrink-0 max-mds:mt-20">
          <p className="text-center">© 2023 My Online Diary</p>
        </footer>
      </body>
    </html>
  );
}
